### ISSUE TITLE
Incorrect SHA256 Hash for Version 2.0.368

### ISSUE THREAD

**Issue by lajoie** [jenkins-x/homebrew-jx#1476]
It looks like the SHA256 hash for v 2.0.368 is incorrect.  Here's what brew reports:

Expected: 46b8fbb6166cc1ba4a29d2f386bf91104d6d0b24771a684f0d13d472095cb353
Actual: 31def64bc583ceee767b463d414d12af25e4aa2ad62db08c169935ec707bb11b

I downloaded the file directly and hashed it and got the same actual value, just to double check.

**Comment by hansanghoon** [comment]
Managed to install previous version with command 
`brew install https://raw.githubusercontent.com/jenkins-x/homebrew-jx/v0.0.271/Formula/jx.rb` 
Also, several recent tags in `jx.rb` looks like have same SHA256 hash value.

**Comment by cagiti** [comment]
see https://github.com/jenkins-x/jx/issues/4503 for more information, closing this as a duplicate
